# Generated by Django 5.2 on 2025-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantroom',
            name='max_capacity',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
