# Generated by Django 5.2 on 2025-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivationapp', '0002_alter_plantroom_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantroom',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plantroom',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
